#!/bin/bash

## Description: Flush caches of all installed TYPO3 instances
## Usage: cache-clear
## Example: ddev cache-clear

for v in v13 v14; do
    if [ -x /var/www/html/$v/vendor/bin/typo3 ]; then
        echo "Flushing $v"
        /var/www/html/$v/vendor/bin/typo3 cache:flush
    fi
done
