#!/bin/bash

VERSION=v9
DATABASE=database_${VERSION}

rm -rf /var/www/html/$VERSION/*
mysql -uroot -proot -e "DROP DATABASE IF EXISTS $DATABASE"

cd /var/www/html/$VERSION

composer init --name=sourcebroker/typo3$VERSION --description=TYPO3$VERSION -n -d /var/www/html/$VERSION
composer config extra.typo3/cms.web-dir public -d /var/www/html/$VERSION
composer config repositories.$EXTENSION_KEY path ../$EXTENSION_KEY -d /var/www/html/$VERSION

composer req typo3/minimal:'^9.5' helhum/typo3-console:'^5.8' jigal/t3adminer:'^9.4' georgringer/news:'^8.0' sourcebroker/translatr:'@dev' --no-progress -n -d /var/www/html/$VERSION

vendor/bin/typo3cms install:setup -n --database-name $DATABASE
vendor/bin/typo3cms configuration:set 'BE/debug' 1
vendor/bin/typo3cms configuration:set 'BE/lockSSL' true
vendor/bin/typo3cms configuration:set 'FE/debug' 1
vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'
vendor/bin/typo3cms install:generatepackagestates

printf '<?php\n\\TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::addPageTSConfig("\n tx_translatr {\n      languages {\n        pl = Polish\n        de = Deutsch\n        fr = French\n      }\n\n      extensions {\n        10 = news\n      }\n}\n");\n' > /var/www/html/$VERSION/public/typo3conf/AdditionalConfiguration.php

vendor/bin/typo3cms database:updateschema
vendor/bin/typo3cms cache:flush
