services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SourceBroker\Translatr\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/{Model,Event,Exception}/*'

  SourceBroker\Translatr\Command\ImportConfigurationCommand:
    tags:
      - name: 'console.command'
        command: 'translatr:import:configuration'
        description: 'Import configuration for labels for ext:translatr'

