name: translatr
type: php
docroot: ~
no_project_mount: true
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
composer_version: 2
additional_hostnames:
    - v9.translatr
    - v10.translatr
    - v11.translatr
additional_fqdns: []
provider: default
use_dns_when_possible: true
extra_services:
    - v9-data
    - v10-data
    - v11-data
hooks:
    pre-start:
        - exec-host: "mkdir -p .test/v9 .test/v10 .test/v11"
        - exec-host: "[ -L .test/translatr ] || ln -snvf ../. .test/translatr"
    post-start:
        - exec: sudo sed -i '1s/^/TERM=xterm-256color\n/' ~/.bashrc

